# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='rank',
        ),
    ]
