# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171202_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('Herald', 'Herald'), ('Guardian', 'Guardian'), ('Crusader', 'Crusader'), ('Archon', 'Archon'), ('Legend', 'Legend'), ('Ancient', 'Ancient'), ('Divine', 'Divine')], default='Herald', max_length=10),
        ),
    ]
